#ifndef HPC22_CONSTANTS_H
#define HPC22_CONSTANTS_H

#define GRAVITATIONAL_CONSTANT 0.00001f
#define OCTREE_MAXDEPTH 12
#define NUM_PARTICLES 5056
#define THETA_SQUARED 0.49f
// #define SPATIAL_IMBALANCE

#endif // HPC22_CONSTANTS_H
